defmodule Krait.GitHub.PRRendererTest do
  use ExUnit.Case, async: true

  alias Krait.GitHub.PRRenderer

  describe "render/1" do
    test "renders full proposal with all fields" do
      proposal = %{
        spec: %{skill_name: "web_fetch", description: "Adds URL fetching capability"},
        ast_hash: "abc123def456",
        complexity: 12,
        security_findings: [%{type: "warning", message: "Uses HTTP"}],
        taint_flows: [%{source: "input", sink: "output"}]
      }

      output = PRRenderer.render(proposal)

      assert output =~ "## Evolution: web_fetch"
      assert output =~ "Adds URL fetching capability"
      assert output =~ "`abc123def456`"
      assert output =~ "12"
      assert output =~ "Security Findings**: 1"
      assert output =~ "Taint Flows**: 1"
      assert output =~ "krait-evolution"
      assert output =~ "needs-human-review"
      assert output =~ "Generated by Krait Evolution System"
    end

    test "renders proposal with string keys in spec" do
      proposal = %{
        spec: %{"skill_name" => "filesystem", "description" => "File ops skill"},
        ast_hash: "hash789",
        complexity: 5,
        security_findings: [],
        taint_flows: []
      }

      output = PRRenderer.render(proposal)

      assert output =~ "## Evolution: filesystem"
      assert output =~ "File ops skill"
      assert output =~ "Security Findings**: 0"
      assert output =~ "Taint Flows**: 0"
    end

    test "renders proposal with nil spec fields gracefully" do
      proposal = %{
        spec: %{},
        ast_hash: "hash000",
        complexity: 0,
        security_findings: nil,
        taint_flows: nil
      }

      output = PRRenderer.render(proposal)

      assert output =~ "## Evolution: Unknown"
      assert output =~ "Security Findings**: 0"
      assert output =~ "Taint Flows**: 0"
    end

    test "renders proposal with nil spec" do
      proposal = %{
        spec: nil,
        ast_hash: "deadbeef",
        complexity: 99,
        security_findings: [],
        taint_flows: []
      }

      # spec is nil, so it falls back to %{} via ||
      output = PRRenderer.render(proposal)

      assert output =~ "## Evolution: Unknown"
      assert output =~ "`deadbeef`"
      assert output =~ "99"
    end

    test "renders proposal with many security findings" do
      findings = Enum.map(1..15, fn i -> %{type: "warning", message: "Finding #{i}"} end)
      taint_flows = Enum.map(1..3, fn i -> %{source: "src#{i}", sink: "sink#{i}"} end)

      proposal = %{
        spec: %{skill_name: "risky_skill", description: "A risky skill"},
        ast_hash: "riskhash",
        complexity: 50,
        security_findings: findings,
        taint_flows: taint_flows
      }

      output = PRRenderer.render(proposal)

      assert output =~ "Security Findings**: 15"
      assert output =~ "Taint Flows**: 3"
    end

    test "includes all expected markdown sections" do
      proposal = %{
        spec: %{skill_name: "test", description: "desc"},
        ast_hash: "h",
        complexity: 1,
        security_findings: [],
        taint_flows: []
      }

      output = PRRenderer.render(proposal)

      assert output =~ "## Evolution:"
      assert output =~ "### Security Analysis"
      assert output =~ "### Labels"
      assert output =~ "---"
    end

    test "renders zero complexity" do
      proposal = %{
        spec: %{skill_name: "simple", description: "Very simple"},
        ast_hash: "0000",
        complexity: 0,
        security_findings: [],
        taint_flows: []
      }

      output = PRRenderer.render(proposal)
      assert output =~ "**Complexity**: 0"
    end
  end

  describe "v22 SEC-17: PR body sanitization" do
    test "long description is truncated" do
      long_desc = String.duplicate("a", 1500)

      proposal = %{
        spec: %{skill_name: "test", description: long_desc},
        ast_hash: "abc",
        complexity: 1,
        security_findings: [],
        taint_flows: []
      }

      output = PRRenderer.render(proposal)
      # The description in the output should be at most 1000 chars
      refute output =~ String.duplicate("a", 1001)
    end

    test "HTML tags are stripped" do
      proposal = %{
        spec: %{skill_name: "test", description: "Hello <script>alert('xss')</script> world"},
        ast_hash: "abc",
        complexity: 1,
        security_findings: [],
        taint_flows: []
      }

      output = PRRenderer.render(proposal)
      refute output =~ "<script>"
      assert output =~ "Hello"
      assert output =~ "alert('xss')"
      assert output =~ "world"
    end

    test "markdown image injection stripped" do
      proposal = %{
        spec: %{
          skill_name: "test",
          description: "Check ![exploit](http://evil.com/track.png) this"
        },
        ast_hash: "abc",
        complexity: 1,
        security_findings: [],
        taint_flows: []
      }

      output = PRRenderer.render(proposal)
      refute output =~ "![exploit]"
      refute output =~ "evil.com"
    end

    test "markdown link injection simplified to text only" do
      proposal = %{
        spec: %{
          skill_name: "test",
          description: "Visit [click here](http://evil.com) for details"
        },
        ast_hash: "abc",
        complexity: 1,
        security_findings: [],
        taint_flows: []
      }

      output = PRRenderer.render(proposal)
      assert output =~ "click here"
      refute output =~ "evil.com"
    end

    test "normal description passes through unchanged" do
      proposal = %{
        spec: %{skill_name: "weather", description: "Check the weather forecast"},
        ast_hash: "abc",
        complexity: 1,
        security_findings: [],
        taint_flows: []
      }

      output = PRRenderer.render(proposal)
      assert output =~ "Check the weather forecast"
    end

    test "sanitize_for_markdown escapes triple backticks" do
      result = PRRenderer.sanitize_for_markdown("code ```elixir\nIO.puts('hi')```", 500)
      refute result =~ "```"
    end
  end
end
