defmodule KraitWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :krait

  # Session cookies are signed AND encrypted.
  # Dev/test use hardcoded salts; prod requires env vars (see runtime.exs).
  # v21 M-10: max_age limits session lifetime to 1 hour (3600 seconds)
  # v23 L-6: Explicit http_only: true for documentation (Phoenix default)
  # v27 L-2: secure: true in prod (HTTPS-only cookies), false in dev/test (localhost HTTP)
  @session_options [
    store: :cookie,
    key: "_krait_key",
    signing_salt: "dev_default_session_salt",
    encryption_salt: "dev_default_encryption_salt",
    same_site: "Strict",
    http_only: true,
    max_age: 3600,
    secure: Application.compile_env(:krait, :env) == :prod
  ]

  @doc """
  Returns session options with runtime overrides merged over compile-time defaults.

  Used by LiveView socket configuration to pick up production salts set in runtime.exs.
  """
  def session_options do
    KraitWeb.Plugs.RuntimeSession.merged_session_opts(@session_options)
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :krait,
    gzip: not code_reloading?,
    only: KraitWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    # v24 F-16: Removed :multipart (unused, reduces attack surface)
    parsers: [:urlencoded, :json],
    # v20 L-4: Restrict to expected content types only
    pass: ["text/html", "application/json"],
    json_decoder: Phoenix.json_library(),
    # v25 L-8: Limit body size to 1MB
    length: 1_000_000

  # v25 L-8: Reject deeply nested JSON after parsing (max 20 levels)
  plug KraitWeb.Plugs.JsonDepthLimit, max_depth: 20

  # v24 F-15: Plug.MethodOverride moved to :browser pipeline in router.ex
  plug Plug.Head
  plug KraitWeb.Plugs.RuntimeSession, @session_options
  plug KraitWeb.Router
end
