import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :krait, KraitWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  # v20 M-3: Allow specific origins instead of disabling check entirely
  check_origin: ["//localhost:4000", "//localhost:4001", "//127.0.0.1:4000"],
  code_reloader: true,
  debug_errors: true,
  # v26 M-2: Generate random dev secrets on each boot — never ship hardcoded secrets
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") ||
      Base.encode64(:crypto.strong_rand_bytes(48)),
  live_view: [signing_salt: Base.encode64(:crypto.strong_rand_bytes(16))],
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :krait, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :krait, Krait.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "krait_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Narsil MCP binary path for deep analysis
# Set to the path of your local narsil-mcp binary, or leave as "narsil-mcp"
# to search PATH. Deep analysis degrades gracefully if unavailable.
config :krait, Krait.Analyzer.Deep,
  narsil_binary:
    System.get_env("NARSIL_BINARY") ||
      System.find_executable("narsil-mcp") ||
      Path.expand("../../narsil-mcp/target/release/narsil-mcp", __DIR__)

# v20 H-2: Removed DeepStub override — real Deep analyzer is conditional in application.ex
# Deep analysis degrades gracefully when narsil-mcp binary is unavailable

# v26 L-2: Random admin session salt per boot
config :krait, :admin_session_salt, Base.encode64(:crypto.strong_rand_bytes(16))

# Sandbox: compile+test generated code in Docker sandbox (same as prod).
# Set KRAIT_DEV_HOST_EXEC=true to opt into host execution for faster iteration.
config :krait, sandbox_enabled: true
config :krait, allow_local_execution: System.get_env("KRAIT_DEV_HOST_EXEC") == "true"
config :krait, accept_host_execution_risk: System.get_env("KRAIT_DEV_HOST_EXEC") == "true"

# v24 F-13: Block PR creation in dev when Narsil is unavailable
config :krait, require_deep_scan: true

# Use dry-run GitHub client unless real credentials are configured
config :krait, github_client: Krait.GitHub.DryRunClient

# Route all LLM tasks through OpenRouter (no local Ollama required)
config :krait, Krait.LLM.Router,
  local_module: Krait.LLM.Ollama,
  cloud_module: Krait.LLM.OpenRouter,
  force_cloud: [:planning, :reflection, :retry_guide, :code_gen, :test_gen, :chat, :retry],
  force_local: [],
  escalation_threshold: 1

# GLM-5 via Novita FP8 (cost-effective, US servers)
config :krait, Krait.LLM.OpenRouter,
  base_url: "https://openrouter.ai/api/v1",
  model: "z-ai/glm-5",
  site_name: "Krait",
  request_timeout: 120_000,
  default_provider: %{
    data_collection: "deny",
    order: ["Novita"],
    quantizations: ["fp8"],
    allow_fallbacks: true
  }
