defmodule Krait.Evolution.Feed do
  @moduledoc "Records and displays evolution events as a shareable feed"

  import Ecto.Query

  alias Krait.Evolution.EventSchema
  alias Krait.Repo

  @spec record(map()) :: {:ok, EventSchema.t()} | {:error, Ecto.Changeset.t()}
  def record(attrs) do
    # Normalize atom keys to string keys for changeset
    attrs = normalize_attrs(attrs)

    changeset = EventSchema.changeset(%EventSchema{}, attrs)

    case Repo.insert(changeset) do
      {:ok, event} ->
        Phoenix.PubSub.broadcast(Krait.PubSub, "evolution:feed", {:evolution_event, event})
        {:ok, event}

      error ->
        error
    end
  end

  @spec list(keyword()) :: [EventSchema.t()]
  def list(opts \\ []) do
    limit = Keyword.get(opts, :limit, 50)

    EventSchema
    |> order_by([e], desc: e.inserted_at)
    |> limit(^limit)
    |> Repo.all()
  end

  @spec to_markdown(EventSchema.t() | map()) :: String.t()
  def to_markdown(event) do
    """
    ## Evolution ##{event.id}: #{event.skill_name}

    **Trigger**: #{event.description}

    **Narsil security scan**: #{Map.get(event, :security_findings, 0) || 0} findings
    **Taint analysis**: #{Map.get(event, :taint_flows, 0) || 0} flows detected
    **Complexity delta**: +#{Map.get(event, :complexity_delta, 0) || 0}
    **Test results**: #{Map.get(event, :test_count, 0) || 0} passing
    **Attempts**: #{Map.get(event, :attempts, 1) || 1}

    **AST Hash**: `#{Map.get(event, :ast_hash, "")}`

    #{safe_pr_link(Map.get(event, :pr_url))}

    ---
    *Generated by Krait Evolution System*
    """
  end

  # v21 M-13: Restrict PR URLs to github.com (aligned with EvolutionLive.safe_pr_url)
  defp safe_pr_link(nil), do: ""

  defp safe_pr_link(url) when is_binary(url) do
    if String.starts_with?(url, "https://github.com/") do
      "[View PR](#{url})"
    else
      ""
    end
  end

  defp safe_pr_link(_), do: ""

  defp normalize_attrs(attrs) when is_map(attrs) do
    Map.new(attrs, fn
      {k, v} when is_atom(k) -> {Atom.to_string(k), v}
      {k, v} -> {k, v}
    end)
  end
end
