defmodule Krait.GitHub.PRRenderer do
  @moduledoc "Generates PR body markdown for evolution proposals"

  @max_description_length 1000
  @max_skill_name_length 100

  def render(validated_proposal) do
    spec = validated_proposal.spec || %{}

    skill_name =
      (Map.get(spec, :skill_name) || Map.get(spec, "skill_name") || "Unknown")
      |> sanitize_for_markdown(@max_skill_name_length)

    description =
      (Map.get(spec, :description) || Map.get(spec, "description") || "")
      |> sanitize_for_markdown(@max_description_length)

    """
    ## Evolution: #{skill_name}

    #{description}

    ### Security Analysis
    - **AST Hash**: `#{validated_proposal.ast_hash}`
    - **Complexity**: #{validated_proposal.complexity}
    - **Security Findings**: #{length(validated_proposal.security_findings || [])}
    - **Taint Flows**: #{length(validated_proposal.taint_flows || [])}

    ### Labels
    `krait-evolution`, `needs-human-review`

    ---
    *Generated by Krait Evolution System*
    """
  end

  @doc """
  Sanitize a string for safe inclusion in markdown PR bodies.

  v22 SEC-17: Truncate, strip HTML tags, strip markdown image/link injection,
  escape triple backticks.
  """
  @spec sanitize_for_markdown(String.t(), pos_integer()) :: String.t()
  def sanitize_for_markdown(text, max_length) when is_binary(text) do
    text
    |> String.slice(0, max_length)
    |> strip_html_tags()
    |> strip_markdown_images()
    |> strip_markdown_links()
    |> escape_triple_backticks()
  end

  def sanitize_for_markdown(text, _max_length), do: to_string(text)

  defp strip_html_tags(text), do: Regex.replace(~r/<[^>]*>/, text, "")
  defp strip_markdown_images(text), do: Regex.replace(~r/!\[[^\]]*\]\([^)]*\)/, text, "")

  defp strip_markdown_links(text),
    do: Regex.replace(~r/\[([^\]]*)\]\([^)]*\)/, text, "\\1")

  defp escape_triple_backticks(text), do: String.replace(text, "```", "\\`\\`\\`")
end
