#!/usr/bin/env bash
set -euo pipefail

# KRAIT Production Secrets Generator
# Generates all required secrets and writes them to .env.prod and .secrets/

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

gen_secret() {
  local length="${1:-64}"
  openssl rand -base64 "$length" | tr -d '\n/+=' | head -c "$length"
}

echo "=== KRAIT Production Secrets Setup ==="
echo ""

# Create secrets directory
mkdir -p "$PROJECT_DIR/.secrets"

# Generate PostgreSQL password
PG_PASSWORD="$(gen_secret 32)"
echo -n "$PG_PASSWORD" > "$PROJECT_DIR/.secrets/pg_password"
chmod 600 "$PROJECT_DIR/.secrets/pg_password"

# Generate all secrets
SECRET_KEY_BASE="$(gen_secret 64)"
SIGNING_SALT="$(gen_secret 32)"
ENCRYPTION_SALT="$(gen_secret 32)"
LIVE_VIEW_SALT="$(gen_secret 32)"
ADMIN_SESSION_SALT="$(gen_secret 32)"
KRAIT_API_TOKEN="$(gen_secret 48)"
KRAIT_ADMIN_TOKEN="$(gen_secret 48)"

# Write .env.prod
ENV_FILE="$PROJECT_DIR/.env.prod"
cat > "$ENV_FILE" << EOF
# KRAIT Production Environment
# Generated by scripts/setup-prod-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# WARNING: This file contains secrets. Do not commit to version control.

# --- Required: Set these manually ---
OPENROUTER_API_KEY=your-openrouter-api-key-here
PHX_HOST=localhost

# --- Database ---
DATABASE_URL=ecto://krait:${PG_PASSWORD}@postgres/krait_prod

# --- Phoenix Secrets ---
SECRET_KEY_BASE=${SECRET_KEY_BASE}
SESSION_SIGNING_SALT=${SIGNING_SALT}
SESSION_ENCRYPTION_SALT=${ENCRYPTION_SALT}
LIVE_VIEW_SALT=${LIVE_VIEW_SALT}
ADMIN_SESSION_SALT=${ADMIN_SESSION_SALT}

# --- Auth Tokens ---
KRAIT_API_TOKEN=${KRAIT_API_TOKEN}
KRAIT_ADMIN_TOKEN=${KRAIT_ADMIN_TOKEN}

# --- Filesystem Sandbox ---
FILESYSTEM_SANDBOX_ROOT=/app/sandbox
EOF

chmod 600 "$ENV_FILE"

echo "Generated secrets:"
echo "  .env.prod              (all environment variables)"
echo "  .secrets/pg_password   (PostgreSQL password)"
echo ""
echo "=== Action Required ==="
echo ""
echo "1. Set your OpenRouter API key:"
echo "   Edit .env.prod and replace 'your-openrouter-api-key-here' with your key"
echo ""
echo "2. Set your hostname:"
echo "   Edit .env.prod and replace 'localhost' with your domain"
echo ""
echo "3. Admin login token (for /admin/login):"
echo "   ${KRAIT_ADMIN_TOKEN}"
echo ""
echo "4. API token (for /api endpoints):"
echo "   ${KRAIT_API_TOKEN}"
echo ""
echo "5. Start the stack:"
echo "   docker compose -f docker-compose.prod.yml up -d"
echo ""
